# Generated by Django 4.2.4 on 2023-11-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
