# Generated by Django 4.2.4 on 2023-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_img',
            field=models.ImageField(max_length=255, null=True, upload_to='courses_img/'),
        ),
    ]
