# Generated by Django 4.2.4 on 2023-11-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrolled_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_course',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enrolled_course',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
