# Generated by Django 4.2.4 on 2023-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrolled_course_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled_course',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolled_course',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
