# Generated by Django 4.2.4 on 2023-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrolled_course_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='creator_id',
            field=models.IntegerField(null=True),
        ),
    ]
