# Generated by Django 4.2.4 on 2023-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='groups',
            field=models.ManyToManyField(related_name='user_details_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_permissions',
            field=models.ManyToManyField(related_name='user_details_set', to='auth.permission'),
        ),
    ]
